Transform: AWS::Serverless-2016-10-31

Description:  A lambda function that executes commands on an EKS cluster (kubctl and helm)

Parameters:
  EnvName:
    Type: String
  KubectlLayerArn:
    Type: String

Resources:
  RunCtlFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Runtime: provided
      Handler: main
      Layers:
        - !Ref KubectlLayerArn
      MemorySize: 512
      #TODO: Tighten policies
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - CloudWatchPutMetricPolicy: {}
        - EKSDescribePolicy: {}
      Environment:
        Variables:
          cluster_name:
            Fn::ImportValue:
              !Sub "BC::${EnvName}::EKS"
          aws_account_id: !Ref "AWS::AccountId"
      Timeout: 30

Outputs:
  RunCtlFuncId:
    Description: RunCtl function id
    Value: !Ref RunCtlFunc
    Export:
      Name: !Sub "BC::${EnvName}::RCTLID"

  RunCtlFuncArn:
    Description: RunCtl function arn
    Value: !GetAtt RunCtlFunc.Arn
    Export:
      Name: !Sub "BC::${EnvName}::RCTLARN"

  RunCtlRoleArn:
    Description: RunCtl role arn
    Value: !GetAtt RunCtlFuncRole.Arn
    Export:
      Name: !Sub "BC::${EnvName}::RCTLROLEARN"

  RunCtlRoleId:
    Description: RunCtl role id
    Value: !GetAtt RunCtlFuncRole.RoleId
    Export:
      Name: !Sub "BC::${EnvName}::RCTLROLEID"